export const DIRECT_SALE_CHECKOUT = "DIRECT_SALE_CHECKOUT";
export const DIRECT_SALE_PRODUCT = "DIRECT_SALE_PRODUCT";
export const DIRECT_SALE_PRODUCT_UPSELL_LIST =
  "DIRECT_SALE_PRODUCT_UPSELL_LIST";
export const SET_ERROR = "SET_ERROR";
