export const DIRECT_SALE_CHECKOUT = "DIRECT_SALE_CHECKOUT";
export const DIRECT_SALE_RESPONSE_CHECKOUT = "DIRECT_SALE_RESPONSE_CHECKOUT";
export const DIRECT_SALE_PRODUCT = "DIRECT_SALE_PRODUCT";
export const DIRECT_SALE_PRODUCT_UPSELL_LIST =
  "DIRECT_SALE_PRODUCT_UPSELL_LIST";
export const SET_SHOPPING_CART = "SET_SHOPPING_CART";
export const SET_ITEM_SHOPPING_CART = "SET_ITEM_SHOPPING_CART";
export const SET_ERROR = "SET_ERROR";
