export const GET_PROFIT = "GET_PROFIT";
export const GET_TODAYS_PROFIT = "GET_TODAYS_PROFIT";
export const GET_AVAILABLE_AMOUNT = "GET_AVAILABLE_AMOUNT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_ERROR = "SET_ERROR";
