export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_ERROR = "SET_ERROR";
export const SET_ITEM_CREATE = "SET_ITEM_CREATE";
export const SET_ITEM_UPDATE = "SET_ITEM_UPDATE";
export const SET_ITEM_DELETE = "SET_ITEM_DELETE";